// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfxwsqfobdewcbwjkmfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmeHdzcWZvYmRld2Nid2prbWZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTk4NzksImV4cCI6MjA3MDY3NTg3OX0.JOuQvgZhkL3dne5BIaywydif71NvO9bXfXtyUNwYiFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});